version: "3.9"

services:
  toolhub:
    image: ghcr.io/wirrockendigital/toolhub:latest
    container_name: toolhub
    hostname: toolhub
    restart: always
    stdin_open: true
    tty: true
    expose:
      - "22"
      - "5656"
    ports:
      - "2222:22"
      - "5656:5656"
    user: "1061:100"
    volumes:
      - /volume1/docker/toolhub:/workspace
      - /volume1/docker/shared:/shared
      - /volume1/docker/toolhub/scripts:/scripts
      - /volume1/docker/toolhub/cron.d:/etc/cron.d
      - /volume1/docker/toolhub/logs:/logs
    networks:
      alle-meine-docker-net:
        ipv4_address: 192.168.128.100

networks:
  alle-meine-docker-net:
    external: true
