version: "3.9"

services:
  toolhub:
    image: ghcr.io/wirrockendigital/toolhub:latest
    container_name: toolhub
    hostname: toolhub
    restart: always
    stdin_open: true
    tty: true
    expose:
      - "22"
      - "5656"
    ports:
      - "2222:22"
      - "5656:5656"
    volumes:
      - /volume1/docker/toolhub:/workspace
      - /volume1/docker/toolhub/shared:/shared
      - /volume1/docker/toolhub/scripts:/scripts
      - /volume1/docker/toolhub/cron.d:/etc/cron.d
      - /volume1/docker/toolhub/logs:/logs
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:5656/test || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      allmydocker-net:
        ipv4_address: 192.168.123.100

networks:
  allmydocker-net:
    external: true