#!/usr/bin/env python3
"""CLI wrapper for Toolhub docx-render Python handler."""
#==MCP==
# {
#   "description": "Render a DOCX template by replacing {{PLACEHOLDER}} values from JSON data.",
#   "schema": {
#     "type": "object",
#     "properties": {
#       "template": { "type": "string", "description": "Template filename located under /data/templates." },
#       "output_name": { "type": "string", "description": "Optional output filename; autogenerated when omitted." },
#       "data": {
#         "type": "object",
#         "description": "Placeholder values as a key/value mapping.",
#         "additionalProperties": { "type": "string" }
#       },
#       "payload": { "type": "string", "description": "Raw JSON payload as alternative input." },
#       "payload_file": { "type": "string", "description": "Path to a JSON payload file as alternative input." }
#     }
#   }
# }
#==/MCP==

import argparse
import json
import os
import sys


# Ensure project modules can be imported in container and local-dev modes.
TOOLS_ROOT = os.getenv("TOOLHUB_PYTHON_ROOT", "/opt/toolhub")
if not os.path.isdir(TOOLS_ROOT) and os.path.isdir("/workspace"):
    TOOLS_ROOT = "/workspace"
if not os.path.isdir(TOOLS_ROOT):
    TOOLS_ROOT = os.getcwd()
if TOOLS_ROOT not in sys.path:
    sys.path.append(TOOLS_ROOT)

from tools.docx_render import handler  # noqa: E402


def load_payload(args: argparse.Namespace) -> dict:
    """Load payload from CLI JSON string/file or explicit fields."""
    # Prefer complete payload input when provided by caller.
    if args.payload:
        return json.loads(args.payload)
    if args.payload_file:
        with open(args.payload_file, "r", encoding="utf-8") as fh:
            return json.load(fh)

    if not args.template:
        raise ValueError("Either --payload/--payload-file or --template is required.")

    # Accept placeholder data from inline JSON or from a dedicated file.
    data_value = {}
    if args.data:
        data_value = json.loads(args.data)
    elif args.data_file:
        with open(args.data_file, "r", encoding="utf-8") as fh:
            data_value = json.load(fh)

    return {
        "template": args.template,
        "output_name": args.output_name,
        "data": data_value,
    }


def main() -> int:
    """Run docx-render handler and print JSON result."""
    parser = argparse.ArgumentParser(description="Run Toolhub docx-render handler.")
    parser.add_argument("--payload", help="Inline JSON payload.")
    parser.add_argument("--payload-file", help="Path to JSON payload file.")
    parser.add_argument("--template", help="Template filename.")
    parser.add_argument("--output-name", help="Optional output filename.")
    parser.add_argument("--data", help="Inline JSON object with placeholder values.")
    parser.add_argument("--data-file", help="Path to JSON file with placeholder values.")
    args = parser.parse_args()

    try:
        payload = load_payload(args)
        result = handler(payload)
        print(json.dumps(result, ensure_ascii=False))
        return 0 if isinstance(result, dict) and result.get("status") == "ok" else 1
    except Exception as exc:  # noqa: BLE001
        print(json.dumps({"status": "error", "error": str(exc)}))
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
